name:  First Workflow
on: [push]

jobs:
    run-shell-commands: 
        runs-on: ubuntu-latest
        steps: 
            - name: echo a string
              run: echo "Eat Chicken"
            - name: multiline Command
              run: |
                node -v
                npm -v